apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: dcgm-exporter
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - gke-managed-system
  selector:
    matchLabels:
      app.kubernetes.io/name: gke-managed-dcgm-exporter
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 15s
