apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: vllm-pod-monitor
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - vllm
  selector:
    matchLabels:
      app: vllm-server
  podMetricsEndpoints:
    - targetPort: 8000
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
