apiVersion: v1
kind: Service
metadata:
  name: agent-service
  namespace: agent
  labels:
    app: agent-server
  annotations:
    cloud.google.com/backend-config: '{"default": "agent-backend-config"}'
spec:
  type: LoadBalancer
  selector:
    app: agent-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
